package ORM;
// Generated Apr 30, 2018 11:39:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idInvoice;
     private String invoiceNo;
     private String invoiceDate;
     private Double subtotal;
     private Double discount;
     private Double netTotal;
     private String isDelete;
     private String createdBy;
     private String invoiceStatus;
     private String invoiceTime;
     private String paymentType;
     private String promoCode;
     private String invoiceType;
     private String serviceNameForPrint;
     private Double serviceQty;
     private Double serviceUnitTotal;
     private Set invoicePaymentInfos = new HashSet(0);
     private Set invoiceItemses = new HashSet(0);
     private Set invoiceCancels = new HashSet(0);
     private Set invoiceHasCreditCards = new HashSet(0);
     private Set customerReturns = new HashSet(0);
     private Set customerHasInvoices = new HashSet(0);
     private Set invoicePayments = new HashSet(0);

    public Invoice() {
    }

    public Invoice(String invoiceNo, String invoiceDate, Double subtotal, Double discount, Double netTotal, String isDelete, String createdBy, String invoiceStatus, String invoiceTime, String paymentType, String promoCode, String invoiceType, String serviceNameForPrint, Double serviceQty, Double serviceUnitTotal, Set invoicePaymentInfos, Set invoiceItemses, Set invoiceCancels, Set invoiceHasCreditCards, Set customerReturns, Set customerHasInvoices, Set invoicePayments) {
       this.invoiceNo = invoiceNo;
       this.invoiceDate = invoiceDate;
       this.subtotal = subtotal;
       this.discount = discount;
       this.netTotal = netTotal;
       this.isDelete = isDelete;
       this.createdBy = createdBy;
       this.invoiceStatus = invoiceStatus;
       this.invoiceTime = invoiceTime;
       this.paymentType = paymentType;
       this.promoCode = promoCode;
       this.invoiceType = invoiceType;
       this.serviceNameForPrint = serviceNameForPrint;
       this.serviceQty = serviceQty;
       this.serviceUnitTotal = serviceUnitTotal;
       this.invoicePaymentInfos = invoicePaymentInfos;
       this.invoiceItemses = invoiceItemses;
       this.invoiceCancels = invoiceCancels;
       this.invoiceHasCreditCards = invoiceHasCreditCards;
       this.customerReturns = customerReturns;
       this.customerHasInvoices = customerHasInvoices;
       this.invoicePayments = invoicePayments;
    }
   
    public Integer getIdInvoice() {
        return this.idInvoice;
    }
    
    public void setIdInvoice(Integer idInvoice) {
        this.idInvoice = idInvoice;
    }
    public String getInvoiceNo() {
        return this.invoiceNo;
    }
    
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }
    public String getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(String invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    public Double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getNetTotal() {
        return this.netTotal;
    }
    
    public void setNetTotal(Double netTotal) {
        this.netTotal = netTotal;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getInvoiceStatus() {
        return this.invoiceStatus;
    }
    
    public void setInvoiceStatus(String invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }
    public String getInvoiceTime() {
        return this.invoiceTime;
    }
    
    public void setInvoiceTime(String invoiceTime) {
        this.invoiceTime = invoiceTime;
    }
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }
    public String getPromoCode() {
        return this.promoCode;
    }
    
    public void setPromoCode(String promoCode) {
        this.promoCode = promoCode;
    }
    public String getInvoiceType() {
        return this.invoiceType;
    }
    
    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType;
    }
    public String getServiceNameForPrint() {
        return this.serviceNameForPrint;
    }
    
    public void setServiceNameForPrint(String serviceNameForPrint) {
        this.serviceNameForPrint = serviceNameForPrint;
    }
    public Double getServiceQty() {
        return this.serviceQty;
    }
    
    public void setServiceQty(Double serviceQty) {
        this.serviceQty = serviceQty;
    }
    public Double getServiceUnitTotal() {
        return this.serviceUnitTotal;
    }
    
    public void setServiceUnitTotal(Double serviceUnitTotal) {
        this.serviceUnitTotal = serviceUnitTotal;
    }
    public Set getInvoicePaymentInfos() {
        return this.invoicePaymentInfos;
    }
    
    public void setInvoicePaymentInfos(Set invoicePaymentInfos) {
        this.invoicePaymentInfos = invoicePaymentInfos;
    }
    public Set getInvoiceItemses() {
        return this.invoiceItemses;
    }
    
    public void setInvoiceItemses(Set invoiceItemses) {
        this.invoiceItemses = invoiceItemses;
    }
    public Set getInvoiceCancels() {
        return this.invoiceCancels;
    }
    
    public void setInvoiceCancels(Set invoiceCancels) {
        this.invoiceCancels = invoiceCancels;
    }
    public Set getInvoiceHasCreditCards() {
        return this.invoiceHasCreditCards;
    }
    
    public void setInvoiceHasCreditCards(Set invoiceHasCreditCards) {
        this.invoiceHasCreditCards = invoiceHasCreditCards;
    }
    public Set getCustomerReturns() {
        return this.customerReturns;
    }
    
    public void setCustomerReturns(Set customerReturns) {
        this.customerReturns = customerReturns;
    }
    public Set getCustomerHasInvoices() {
        return this.customerHasInvoices;
    }
    
    public void setCustomerHasInvoices(Set customerHasInvoices) {
        this.customerHasInvoices = customerHasInvoices;
    }
    public Set getInvoicePayments() {
        return this.invoicePayments;
    }
    
    public void setInvoicePayments(Set invoicePayments) {
        this.invoicePayments = invoicePayments;
    }




}


