package ORM;
// Generated Apr 30, 2018 11:39:55 AM by Hibernate Tools 4.3.1



/**
 * InvoicePaymentInfo generated by hbm2java
 */
public class InvoicePaymentInfo  implements java.io.Serializable {


     private Integer idInvoicePaymentInfo;
     private Invoice invoice;
     private String cashTenderd;
     private String cashBalance;
     private String custromerPerviusBalance;
     private String isDelete;
     private String totalWithBalance;

    public InvoicePaymentInfo() {
    }

	
    public InvoicePaymentInfo(Invoice invoice) {
        this.invoice = invoice;
    }
    public InvoicePaymentInfo(Invoice invoice, String cashTenderd, String cashBalance, String custromerPerviusBalance, String isDelete, String totalWithBalance) {
       this.invoice = invoice;
       this.cashTenderd = cashTenderd;
       this.cashBalance = cashBalance;
       this.custromerPerviusBalance = custromerPerviusBalance;
       this.isDelete = isDelete;
       this.totalWithBalance = totalWithBalance;
    }
   
    public Integer getIdInvoicePaymentInfo() {
        return this.idInvoicePaymentInfo;
    }
    
    public void setIdInvoicePaymentInfo(Integer idInvoicePaymentInfo) {
        this.idInvoicePaymentInfo = idInvoicePaymentInfo;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public String getCashTenderd() {
        return this.cashTenderd;
    }
    
    public void setCashTenderd(String cashTenderd) {
        this.cashTenderd = cashTenderd;
    }
    public String getCashBalance() {
        return this.cashBalance;
    }
    
    public void setCashBalance(String cashBalance) {
        this.cashBalance = cashBalance;
    }
    public String getCustromerPerviusBalance() {
        return this.custromerPerviusBalance;
    }
    
    public void setCustromerPerviusBalance(String custromerPerviusBalance) {
        this.custromerPerviusBalance = custromerPerviusBalance;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public String getTotalWithBalance() {
        return this.totalWithBalance;
    }
    
    public void setTotalWithBalance(String totalWithBalance) {
        this.totalWithBalance = totalWithBalance;
    }




}


