package ORM;
// Generated Apr 30, 2018 11:39:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Items generated by hbm2java
 */
public class Items  implements java.io.Serializable {


     private Integer idRawItems;
     private ItemCatagory itemCatagory;
     private String itemName;
     private Double itemsUnitPrice;
     private String description;
     private String isDelete;
     private String isRaw;
     private String isService;
     private Double itemsSellingPrice;
     private String itemsCode;
     private Set promotionItemses = new HashSet(0);
     private Set rawItemStocks = new HashSet(0);
     private Set stockOutgoings = new HashSet(0);
     private Set rawItemInfos = new HashSet(0);
     private Set rowGrnItems = new HashSet(0);
     private Set invoiceItemses = new HashSet(0);
     private Set quattionItemses = new HashSet(0);
     private Set orderItemses = new HashSet(0);

    public Items() {
    }

	
    public Items(ItemCatagory itemCatagory) {
        this.itemCatagory = itemCatagory;
    }
    public Items(ItemCatagory itemCatagory, String itemName, Double itemsUnitPrice, String description, String isDelete, String isRaw, String isService, Double itemsSellingPrice, String itemsCode, Set promotionItemses, Set rawItemStocks, Set stockOutgoings, Set rawItemInfos, Set rowGrnItems, Set invoiceItemses, Set quattionItemses, Set orderItemses) {
       this.itemCatagory = itemCatagory;
       this.itemName = itemName;
       this.itemsUnitPrice = itemsUnitPrice;
       this.description = description;
       this.isDelete = isDelete;
       this.isRaw = isRaw;
       this.isService = isService;
       this.itemsSellingPrice = itemsSellingPrice;
       this.itemsCode = itemsCode;
       this.promotionItemses = promotionItemses;
       this.rawItemStocks = rawItemStocks;
       this.stockOutgoings = stockOutgoings;
       this.rawItemInfos = rawItemInfos;
       this.rowGrnItems = rowGrnItems;
       this.invoiceItemses = invoiceItemses;
       this.quattionItemses = quattionItemses;
       this.orderItemses = orderItemses;
    }
   
    public Integer getIdRawItems() {
        return this.idRawItems;
    }
    
    public void setIdRawItems(Integer idRawItems) {
        this.idRawItems = idRawItems;
    }
    public ItemCatagory getItemCatagory() {
        return this.itemCatagory;
    }
    
    public void setItemCatagory(ItemCatagory itemCatagory) {
        this.itemCatagory = itemCatagory;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public Double getItemsUnitPrice() {
        return this.itemsUnitPrice;
    }
    
    public void setItemsUnitPrice(Double itemsUnitPrice) {
        this.itemsUnitPrice = itemsUnitPrice;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public String getIsRaw() {
        return this.isRaw;
    }
    
    public void setIsRaw(String isRaw) {
        this.isRaw = isRaw;
    }
    public String getIsService() {
        return this.isService;
    }
    
    public void setIsService(String isService) {
        this.isService = isService;
    }
    public Double getItemsSellingPrice() {
        return this.itemsSellingPrice;
    }
    
    public void setItemsSellingPrice(Double itemsSellingPrice) {
        this.itemsSellingPrice = itemsSellingPrice;
    }
    public String getItemsCode() {
        return this.itemsCode;
    }
    
    public void setItemsCode(String itemsCode) {
        this.itemsCode = itemsCode;
    }
    public Set getPromotionItemses() {
        return this.promotionItemses;
    }
    
    public void setPromotionItemses(Set promotionItemses) {
        this.promotionItemses = promotionItemses;
    }
    public Set getRawItemStocks() {
        return this.rawItemStocks;
    }
    
    public void setRawItemStocks(Set rawItemStocks) {
        this.rawItemStocks = rawItemStocks;
    }
    public Set getStockOutgoings() {
        return this.stockOutgoings;
    }
    
    public void setStockOutgoings(Set stockOutgoings) {
        this.stockOutgoings = stockOutgoings;
    }
    public Set getRawItemInfos() {
        return this.rawItemInfos;
    }
    
    public void setRawItemInfos(Set rawItemInfos) {
        this.rawItemInfos = rawItemInfos;
    }
    public Set getRowGrnItems() {
        return this.rowGrnItems;
    }
    
    public void setRowGrnItems(Set rowGrnItems) {
        this.rowGrnItems = rowGrnItems;
    }
    public Set getInvoiceItemses() {
        return this.invoiceItemses;
    }
    
    public void setInvoiceItemses(Set invoiceItemses) {
        this.invoiceItemses = invoiceItemses;
    }
    public Set getQuattionItemses() {
        return this.quattionItemses;
    }
    
    public void setQuattionItemses(Set quattionItemses) {
        this.quattionItemses = quattionItemses;
    }
    public Set getOrderItemses() {
        return this.orderItemses;
    }
    
    public void setOrderItemses(Set orderItemses) {
        this.orderItemses = orderItemses;
    }




}


