package ORM;
// Generated Apr 30, 2018 11:39:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer idOrders;
     private Customer customer;
     private String orderNo;
     private String orderDate;
     private String recorrectionDate;
     private String deliveryDate;
     private Double orderTotal;
     private String isDelete;
     private Double advance;
     private String govorderNo;
     private String acceptedBy;
     private String serviceNameForPrint;
     private Double orderQty;
     private Double unitPriceForOrder;
     private Set orderItemses = new HashSet(0);
     private Set orderStatuses = new HashSet(0);

    public Orders() {
    }

	
    public Orders(Customer customer) {
        this.customer = customer;
    }
    public Orders(Customer customer, String orderNo, String orderDate, String recorrectionDate, String deliveryDate, Double orderTotal, String isDelete, Double advance, String govorderNo, String acceptedBy, String serviceNameForPrint, Double orderQty, Double unitPriceForOrder, Set orderItemses, Set orderStatuses) {
       this.customer = customer;
       this.orderNo = orderNo;
       this.orderDate = orderDate;
       this.recorrectionDate = recorrectionDate;
       this.deliveryDate = deliveryDate;
       this.orderTotal = orderTotal;
       this.isDelete = isDelete;
       this.advance = advance;
       this.govorderNo = govorderNo;
       this.acceptedBy = acceptedBy;
       this.serviceNameForPrint = serviceNameForPrint;
       this.orderQty = orderQty;
       this.unitPriceForOrder = unitPriceForOrder;
       this.orderItemses = orderItemses;
       this.orderStatuses = orderStatuses;
    }
   
    public Integer getIdOrders() {
        return this.idOrders;
    }
    
    public void setIdOrders(Integer idOrders) {
        this.idOrders = idOrders;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }
    public String getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }
    public String getRecorrectionDate() {
        return this.recorrectionDate;
    }
    
    public void setRecorrectionDate(String recorrectionDate) {
        this.recorrectionDate = recorrectionDate;
    }
    public String getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(String deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public Double getOrderTotal() {
        return this.orderTotal;
    }
    
    public void setOrderTotal(Double orderTotal) {
        this.orderTotal = orderTotal;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
    public Double getAdvance() {
        return this.advance;
    }
    
    public void setAdvance(Double advance) {
        this.advance = advance;
    }
    public String getGovorderNo() {
        return this.govorderNo;
    }
    
    public void setGovorderNo(String govorderNo) {
        this.govorderNo = govorderNo;
    }
    public String getAcceptedBy() {
        return this.acceptedBy;
    }
    
    public void setAcceptedBy(String acceptedBy) {
        this.acceptedBy = acceptedBy;
    }
    public String getServiceNameForPrint() {
        return this.serviceNameForPrint;
    }
    
    public void setServiceNameForPrint(String serviceNameForPrint) {
        this.serviceNameForPrint = serviceNameForPrint;
    }
    public Double getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(Double orderQty) {
        this.orderQty = orderQty;
    }
    public Double getUnitPriceForOrder() {
        return this.unitPriceForOrder;
    }
    
    public void setUnitPriceForOrder(Double unitPriceForOrder) {
        this.unitPriceForOrder = unitPriceForOrder;
    }
    public Set getOrderItemses() {
        return this.orderItemses;
    }
    
    public void setOrderItemses(Set orderItemses) {
        this.orderItemses = orderItemses;
    }
    public Set getOrderStatuses() {
        return this.orderStatuses;
    }
    
    public void setOrderStatuses(Set orderStatuses) {
        this.orderStatuses = orderStatuses;
    }




}


