package ORM;
// Generated Apr 30, 2018 11:39:55 AM by Hibernate Tools 4.3.1



/**
 * OrderItems generated by hbm2java
 */
public class OrderItems  implements java.io.Serializable {


     private Integer idOrderItems;
     private Items items;
     private Orders orders;
     private Double qty;
     private Double unitPrice;
     private Double netTotalOrdersItem;
     private String isDelete;

    public OrderItems() {
    }

	
    public OrderItems(Items items, Orders orders) {
        this.items = items;
        this.orders = orders;
    }
    public OrderItems(Items items, Orders orders, Double qty, Double unitPrice, Double netTotalOrdersItem, String isDelete) {
       this.items = items;
       this.orders = orders;
       this.qty = qty;
       this.unitPrice = unitPrice;
       this.netTotalOrdersItem = netTotalOrdersItem;
       this.isDelete = isDelete;
    }
   
    public Integer getIdOrderItems() {
        return this.idOrderItems;
    }
    
    public void setIdOrderItems(Integer idOrderItems) {
        this.idOrderItems = idOrderItems;
    }
    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Double getNetTotalOrdersItem() {
        return this.netTotalOrdersItem;
    }
    
    public void setNetTotalOrdersItem(Double netTotalOrdersItem) {
        this.netTotalOrdersItem = netTotalOrdersItem;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


