package ORM;
// Generated Apr 30, 2018 11:39:55 AM by Hibernate Tools 4.3.1



/**
 * PromotionItems generated by hbm2java
 */
public class PromotionItems  implements java.io.Serializable {


     private Integer idPromotionItems;
     private Items items;
     private Promotion promotion;
     private String isDelete;

    public PromotionItems() {
    }

	
    public PromotionItems(Items items, Promotion promotion) {
        this.items = items;
        this.promotion = promotion;
    }
    public PromotionItems(Items items, Promotion promotion, String isDelete) {
       this.items = items;
       this.promotion = promotion;
       this.isDelete = isDelete;
    }
   
    public Integer getIdPromotionItems() {
        return this.idPromotionItems;
    }
    
    public void setIdPromotionItems(Integer idPromotionItems) {
        this.idPromotionItems = idPromotionItems;
    }
    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public Promotion getPromotion() {
        return this.promotion;
    }
    
    public void setPromotion(Promotion promotion) {
        this.promotion = promotion;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


