package ORM;
// Generated Apr 30, 2018 11:39:55 AM by Hibernate Tools 4.3.1



/**
 * QuattionItems generated by hbm2java
 */
public class QuattionItems  implements java.io.Serializable {


     private Integer idOrderItems;
     private Items items;
     private Quatations quatations;
     private Double qty;
     private Double unitPrice;
     private Double netTotalOrdersItem;
     private String isDelete;

    public QuattionItems() {
    }

	
    public QuattionItems(Items items, Quatations quatations) {
        this.items = items;
        this.quatations = quatations;
    }
    public QuattionItems(Items items, Quatations quatations, Double qty, Double unitPrice, Double netTotalOrdersItem, String isDelete) {
       this.items = items;
       this.quatations = quatations;
       this.qty = qty;
       this.unitPrice = unitPrice;
       this.netTotalOrdersItem = netTotalOrdersItem;
       this.isDelete = isDelete;
    }
   
    public Integer getIdOrderItems() {
        return this.idOrderItems;
    }
    
    public void setIdOrderItems(Integer idOrderItems) {
        this.idOrderItems = idOrderItems;
    }
    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public Quatations getQuatations() {
        return this.quatations;
    }
    
    public void setQuatations(Quatations quatations) {
        this.quatations = quatations;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Double getNetTotalOrdersItem() {
        return this.netTotalOrdersItem;
    }
    
    public void setNetTotalOrdersItem(Double netTotalOrdersItem) {
        this.netTotalOrdersItem = netTotalOrdersItem;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


