package ORM;
// Generated Apr 30, 2018 11:39:55 AM by Hibernate Tools 4.3.1



/**
 * RawItemStock generated by hbm2java
 */
public class RawItemStock  implements java.io.Serializable {


     private Integer idStock;
     private Items items;
     private Double qty;
     private String unit;
     private String isDelete;

    public RawItemStock() {
    }

	
    public RawItemStock(Items items) {
        this.items = items;
    }
    public RawItemStock(Items items, Double qty, String unit, String isDelete) {
       this.items = items;
       this.qty = qty;
       this.unit = unit;
       this.isDelete = isDelete;
    }
   
    public Integer getIdStock() {
        return this.idStock;
    }
    
    public void setIdStock(Integer idStock) {
        this.idStock = idStock;
    }
    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }




}


