package ORM;
// Generated Apr 30, 2018 11:39:55 AM by Hibernate Tools 4.3.1



/**
 * RawItemInfo generated by hbm2java
 */
public class RawItemInfo  implements java.io.Serializable {


     private Integer idRawItemInfo;
     private Items items;
     private String minQty;

    public RawItemInfo() {
    }

	
    public RawItemInfo(Items items) {
        this.items = items;
    }
    public RawItemInfo(Items items, String minQty) {
       this.items = items;
       this.minQty = minQty;
    }
   
    public Integer getIdRawItemInfo() {
        return this.idRawItemInfo;
    }
    
    public void setIdRawItemInfo(Integer idRawItemInfo) {
        this.idRawItemInfo = idRawItemInfo;
    }
    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public String getMinQty() {
        return this.minQty;
    }
    
    public void setMinQty(String minQty) {
        this.minQty = minQty;
    }




}


