package ORM;
// Generated Apr 30, 2018 11:39:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RowGrnItem generated by hbm2java
 */
public class RowGrnItem  implements java.io.Serializable {


     private Integer idRowGrnItem;
     private Items items;
     private RawGrn rawGrn;
     private Double rowItemQty;
     private Double grossPrice;
     private Double rowItemTotal;
     private String rowGrnItemUnit;
     private Set supplierReturns = new HashSet(0);

    public RowGrnItem() {
    }

	
    public RowGrnItem(Items items, RawGrn rawGrn) {
        this.items = items;
        this.rawGrn = rawGrn;
    }
    public RowGrnItem(Items items, RawGrn rawGrn, Double rowItemQty, Double grossPrice, Double rowItemTotal, String rowGrnItemUnit, Set supplierReturns) {
       this.items = items;
       this.rawGrn = rawGrn;
       this.rowItemQty = rowItemQty;
       this.grossPrice = grossPrice;
       this.rowItemTotal = rowItemTotal;
       this.rowGrnItemUnit = rowGrnItemUnit;
       this.supplierReturns = supplierReturns;
    }
   
    public Integer getIdRowGrnItem() {
        return this.idRowGrnItem;
    }
    
    public void setIdRowGrnItem(Integer idRowGrnItem) {
        this.idRowGrnItem = idRowGrnItem;
    }
    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public RawGrn getRawGrn() {
        return this.rawGrn;
    }
    
    public void setRawGrn(RawGrn rawGrn) {
        this.rawGrn = rawGrn;
    }
    public Double getRowItemQty() {
        return this.rowItemQty;
    }
    
    public void setRowItemQty(Double rowItemQty) {
        this.rowItemQty = rowItemQty;
    }
    public Double getGrossPrice() {
        return this.grossPrice;
    }
    
    public void setGrossPrice(Double grossPrice) {
        this.grossPrice = grossPrice;
    }
    public Double getRowItemTotal() {
        return this.rowItemTotal;
    }
    
    public void setRowItemTotal(Double rowItemTotal) {
        this.rowItemTotal = rowItemTotal;
    }
    public String getRowGrnItemUnit() {
        return this.rowGrnItemUnit;
    }
    
    public void setRowGrnItemUnit(String rowGrnItemUnit) {
        this.rowGrnItemUnit = rowGrnItemUnit;
    }
    public Set getSupplierReturns() {
        return this.supplierReturns;
    }
    
    public void setSupplierReturns(Set supplierReturns) {
        this.supplierReturns = supplierReturns;
    }




}


